import { IMainPageItem } from '@/interfaces'

export const recommendetItems: IMainPageItem[] = [
	{
		img: '/mainPageIcons/recomendet/videoconference.png',
		link: 'about',
		title: 'Портал дистанционного обучения',
		imgHeight: 57,
		imgWidth: 57,
	},
	{
		img: '/mainPageIcons/recomendet/phone.png',
		link: 'about',
		title: 'Телефонный справочник',
		imgHeight: 57,
		imgWidth: 57,
	},
	{
		img: '/mainPageIcons/recomendet/book-shelf.png',
		link: 'about',
		title: 'Сайт научной библиотеки',
		imgHeight: 59,
		imgWidth: 59,
	},
	{
		img: '/mainPageIcons/recomendet/online-library.png',
		link: 'about',
		title: 'Электронный каталог научной библиотеки',
		imgHeight: 59,
		imgWidth: 59,
	},
	{
		img: '/mainPageIcons/recomendet/newspaper.png',
		link: 'about',
		title: 'Газета “За кадры”',
		imgHeight: 53,
		imgWidth: 50,
	},
	{
		img: '/mainPageIcons/recomendet/newspaper.png',
		link: 'about',
		title: 'Вестник Воронежского ГАУ',
		imgHeight: 52,
		imgWidth: 52,
	},
	{
		img: '/mainPageIcons/recomendet/fake-news.png',
		link: 'about',
		title: 'Zachet. Студенческий медиапортал',
		imgHeight: 57,
		imgWidth: 57,
	},
	{
		img: '/mainPageIcons/recomendet/fake-news.png',
		link: 'about',
		title: 'Zachet. Студенческий медиапортал',
		imgHeight: 57,
		imgWidth: 57,
	},
	{
		img: '/mainPageIcons/recomendet/fake-news.png',
		link: 'about',
		title: 'Zachet. Студенческий медиапортал',
		imgHeight: 57,
		imgWidth: 57,
	},
	{
		img: '/mainPageIcons/recomendet/fake-news.png',
		link: 'about',
		title: 'Zachet. Студенческий медиапортал',
		imgHeight: 57,
		imgWidth: 57,
	},
	{
		img: '/mainPageIcons/recomendet/fake-news.png',
		link: 'about',
		title: 'Zachet. Студенческий медиапортал',
		imgHeight: 57,
		imgWidth: 57,
	},
	{
		img: '/mainPageIcons/recomendet/fake-news.png',
		link: 'about',
		title: 'Zachet. Студенческий медиапортал',
		imgHeight: 57,
		imgWidth: 57,
	},
	{
		img: '/mainPageIcons/recomendet/fake-news.png',
		link: 'about',
		title: 'Zachet. Студенческий медиапортал',
		imgHeight: 57,
		imgWidth: 57,
	},
	{
		img: '/mainPageIcons/recomendet/fake-news.png',
		link: 'about',
		title: 'Zachet. Студенческий медиапортал',
		imgHeight: 57,
		imgWidth: 57,
	},
]
